version: "3"
services:
    mongo:
        image: "mongo"
        container_name: mongo

    crud:
        build: .
        depends_on:
            - mongo
        ports:
            - "5001:5001"
        container_name: crud